### ISSUE TITLE
Extension Not Working in Google Chrome [Manifest version 2 deprecated]

### ISSUE THREAD

**Issue by gigahidjrikaaa** [dundorma/RekDat-EasyMode#1] opened 2023-09-27 17:39 UTC
I've tried this extension on the Chrome browser. It gave an error on the Manifest version.

<img width="481" alt="image" src="https://github.com/dundorma/RekDat-EasyMode/assets/52191436/e98e24b8-5697-434a-be28-3a035cd9d256">

I tried reloading the extension and the chrome browser, but to no avail. It works perfectly in Brave, though. Maybe this is something you want to have a look at 😄

**Comment by dundorma** [comment] 2023-09-27 17:47
The issue is now fixed sir 😁👍🏿

**Closed as completed** 2023-09-27 17:46 UTC
